apiVersion: v1
kind: Service
metadata:
  name: ms-patient
  namespace: ms-patient
spec:
  type: NodePort
  selector:
    app: ms-patient
  ports:
  - port: 8081
    targetPort: 8081
    nodePort: 30081
